#!/usr/bin/env python3
# tests/unigram/gen_grapheme.py: extract the extended-grapheme-cluster tables hf tokenizers 0.23.2 runs
# (unicode-segmentation 1.13.3, Unicode 17.0.0, the crate pinned by bindings/python/Cargo.lock of hf's
# v0.23.2 tag) into tests/data/unigram/grapheme17.txt. The Precompiled normalizer walks the text grapheme by
# grapheme (docs/algorithms/unigram.md §3), so these tables are part of its definition.
#
#   uv run tests/unigram/gen_grapheme.py            # downloads the crate (pinned sha256), rewrites the table
#   uv run tests/unigram/gen_grapheme.py --check    # exits 1 when the checked-in table differs
#
# Output lines (code points in hex, ranges inclusive):
#   C <lo> <hi> <cat>     grapheme_cat_table entry; cat is the crate's GraphemeCat without "GC_"
#   E <lo> <hi>           InCB_Extend_table entry
#   K <cp>                is_incb_linker member
# Code points in no C range are GC_Any (the crate's default).
#
# /// script
# requires-python = ">=3.10"
# ///

from __future__ import annotations

import hashlib
import io
import os
import re
import sys
import tarfile
import urllib.request

CRATE = "unicode-segmentation"
VERSION = "1.13.3"
SHA256 = "c6f5d3c3b1bf09027a88a6bc961fc00497d651009560b5463668dc81b0fa87a8"  # hf v0.23.2 Cargo.lock checksum
URL = f"https://static.crates.io/crates/{CRATE}/{CRATE}-{VERSION}.crate"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "unigram", "grapheme17.txt")


def tables_rs() -> str:
    with urllib.request.urlopen(URL, timeout=120) as r:
        blob = r.read()
    got = hashlib.sha256(blob).hexdigest()
    if got != SHA256:
        raise SystemExit(f"crate sha256 {got} != pinned {SHA256}")
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as t:
        f = t.extractfile(f"{CRATE}-{VERSION}/src/tables.rs")
        assert f is not None
        return f.read().decode("utf-8")


def block(src: str, name: str) -> str:
    i = src.index(f"const {name}:")
    j = src.index("];", i)
    return src[i:j]


def render(src: str) -> str:
    ver = re.search(r"pub const UNICODE_VERSION: \(u64, u64, u64\) = \((\d+), (\d+), (\d+)\);", src)
    assert ver is not None
    out = [f"# {CRATE} {VERSION} (crate sha256 {SHA256}), src/tables.rs, UNICODE_VERSION "
           f"{ver.group(1)}.{ver.group(2)}.{ver.group(3)}; generated by tests/unigram/gen_grapheme.py",
           "# C lo hi cat (grapheme_cat_table; default Any) / E lo hi (InCB_Extend) / K cp (InCB linker)"]
    cats = re.findall(r"\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}',\s*GC_(\w+)\)", block(src, "grapheme_cat_table"))
    assert len(cats) > 1000
    prev = -1
    for lo, hi, cat in cats:  # bounded by the table length
        a, b = int(lo, 16), int(hi, 16)
        assert prev < a <= b, (lo, hi)
        prev = b
        out.append(f"C {a:x} {b:x} {cat}")
    ext = re.findall(r"\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}'\)", block(src, "InCB_Extend_table"))
    assert len(ext) > 50
    for lo, hi in ext:
        out.append(f"E {int(lo, 16):x} {int(hi, 16):x}")
    i = src.index("pub fn is_incb_linker")
    j = src.index("\n}", i)
    linkers = re.findall(r"'\\u\{([0-9a-fA-F]+)\}'", src[i:j])
    assert len(linkers) >= 6
    for cp in linkers:
        out.append(f"K {int(cp, 16):x}")
    return "\n".join(out) + "\n"


CATS = ["Any", "CR", "Control", "Extend", "Extended_Pictographic", "InCB_Consonant", "L", "LF", "LV", "LVT",
        "Prepend", "Regional_Indicator", "SpacingMark", "T", "V", "ZWJ"]  # = TOKS_GC_* in src/core/unigram.h
C_OUT = os.path.join(HERE, "..", "..", "src", "gen", "grapheme17.c")


def emit_c(table: str) -> None:
    """src/gen/grapheme17.c: class byte per code point (cat | 0x10 InCB=Extend | 0x20 InCB=Linker), two-stage"""
    cls = bytearray(0x110000)
    for line in table.splitlines():  # bounded by the table
        if line.startswith("#") or not line.strip():
            continue
        p = line.split()
        if p[0] == "C":
            v = CATS.index(p[3])
            for cp in range(int(p[1], 16), int(p[2], 16) + 1):
                cls[cp] = (cls[cp] & 0xF0) | v
        elif p[0] == "E":
            for cp in range(int(p[1], 16), int(p[2], 16) + 1):
                cls[cp] |= 0x10
        elif p[0] == "K":
            cls[int(p[1], 16)] |= 0x20
    blocks = {}
    stage1 = []
    order = []
    for b in range(0x1100):
        blk = bytes(cls[b * 256:(b + 1) * 256])
        if blk not in blocks:
            blocks[blk] = len(order)
            order.append(blk)
        stage1.append(blocks[blk])
    sha = hashlib.sha256(table.encode()).hexdigest()
    out = ["/* generated by tests/unigram/gen_grapheme.py --c from tests/data/unigram/grapheme17.txt",
           f" * (sha256 {sha}): unicode-segmentation {VERSION}, Unicode 17.0.0. Do not edit. */",
           "#include <stdint.h>", "",
           "extern const uint16_t TOKS_GC_STAGE1[0x1100];",
           f"extern const uint8_t TOKS_GC_STAGE2[{len(order) * 256}];", "",
           "const uint16_t TOKS_GC_STAGE1[0x1100] = {"]
    for i in range(0, len(stage1), 16):
        out.append("    " + ", ".join(str(x) for x in stage1[i:i + 16]) + ",")
    out.append("};")
    out.append(f"const uint8_t TOKS_GC_STAGE2[{len(order) * 256}] = {{")
    for blk in order:
        for i in range(0, 256, 32):
            out.append("    " + ",".join(str(x) for x in blk[i:i + 32]) + ",")
    out.append("};")
    os.makedirs(os.path.dirname(C_OUT), exist_ok=True)
    with open(C_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {C_OUT}: {len(order)} blocks ({len(order) * 256 + 2 * 0x1100} bytes)")


def main() -> None:
    if "--c" in sys.argv:
        with open(OUT, encoding="utf-8") as f:
            emit_c(f.read())
        return
    text = render(tables_rs())
    if "--check" in sys.argv:
        with open(OUT, encoding="utf-8") as f:
            ok = f.read() == text
        print("grapheme17.txt", "matches the crate" if ok else "DIFFERS from the crate")
        sys.exit(0 if ok else 1)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {OUT}: {text.count(chr(10))} lines, sha256 {hashlib.sha256(text.encode()).hexdigest()[:16]}")


if __name__ == "__main__":
    main()
