"""tests/wordpiece/golden_decode.py: writes tests/data/wordpiece/decode_golden.inc, hf tokenizers 0.23.2's decode of
random id sequences over a small WordPiece tokenizer whose strings are built to stress the WordPiece decoder: the
prefix rule and hf's cleanup (eleven str::replace passes in order, wordpiece.md §8), including strings with inner
spaces where one pass's output feeds a later pass's match, added tokens (special, normalized with a form that
differs from the content) and a no-decoder variant.

    uv run --with tokenizers==0.23.2 python tests/wordpiece/golden_decode.py

tests/c/test_wp.c loads each tokenizer through toks_load_mem_copy and checks toks_decode against these bytes.
"""
import json
import os
import random

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "data", "wordpiece", "decode_golden.inc")

STRINGS = ["[UNK]", "[CLS]", "[SEP]", "a", "b", "##b", "##", "###", " ", "  ", ".", " .", "..", "?", " ?", "!", " !",
           ",", " ,", "'", " '", "' ", " ' ", "' '", "'s", " 's", "##'s", "'m", " 'm", "'ve", " 've", "'re", " 're",
           "n't", " n't", "##n't", "do", " do", "do not", " do not", "not", "don't", "x y", "x  y", " . ,", "s", "m",
           "ve", "re", "t", "n", "##.", "##,", "##'", "## ", "é", "##é", " ' s", " 'sx", "x 's 'm", ". ?", " ' ' '",
           "do not do not", " do  not", "''", "' ' ' "]


def tokenizer_json(decoder, added, lowercase=True):
    vocab = {s: i for i, s in enumerate(STRINGS)}
    return {
        "version": "1.0", "truncation": None, "padding": None,
        "added_tokens": added,
        "normalizer": {"type": "BertNormalizer", "clean_text": True, "handle_chinese_chars": True,
                       "strip_accents": None, "lowercase": lowercase},
        "pre_tokenizer": {"type": "BertPreTokenizer"},
        "post_processor": None,
        "decoder": decoder,
        "model": {"type": "WordPiece", "unk_token": "[UNK]", "continuing_subword_prefix": "##",
                  "max_input_chars_per_word": 100, "vocab": vocab},
    }


def added(content, tid, special, normalized):
    return {"id": tid, "content": content, "single_word": False, "lstrip": False, "rstrip": False,
            "normalized": normalized, "special": special}


VARIANTS = [
    ("cleanup", {"type": "WordPiece", "prefix": "##", "cleanup": True},
     [added("[CLS]", 1, True, False), added("[SEP]", 2, True, False)]),
    ("nocleanup", {"type": "WordPiece", "prefix": "##", "cleanup": False}, [added("[CLS]", 1, True, False)]),
    ("prefix_empty", {"type": "WordPiece", "prefix": "", "cleanup": True}, []),
    ("prefix_quote", {"type": "WordPiece", "prefix": "'", "cleanup": True}, []),
    ("nodecoder", None, [added("[SEP]", 2, True, False)]),
    # a normalized special whose form differs ("[MASK]" -> "[mask]"): hf prints the form and does not skip it;
    # a normalized non-special whose form equals a special's content ("[SEP]" lowercased is not "[SEP]": use
    # "[cls]" as the special content so the form "[cls]" of "[CLS]" matches it)
    ("forms", {"type": "WordPiece", "prefix": "##", "cleanup": True},
     [added("[cls]", len(STRINGS), True, False), added("[CLS]", 1, False, True), added("[MASK]", len(STRINGS) + 1, True, True),
      added("Hello World", len(STRINGS) + 2, False, True)]),
]


def c_bytes(b):
    out = []
    for x in b:
        if x in (0x22, 0x5C) or x < 0x20 or x >= 0x7F or x == 0x3F:
            out.append("\\%03o" % x)
        else:
            out.append(chr(x))
    return '"' + "".join(out) + '"'


def main():
    rng = random.Random(1)
    lines = ["/* generated by tests/wordpiece/golden_decode.py from hf tokenizers 0.23.2; do not edit */"]
    lines.append("static const char *const DEC_JSON[] = {")
    jsons = []
    for name, dec, add in VARIANTS:
        js = json.dumps(tokenizer_json(dec, add), ensure_ascii=False)
        jsons.append(js)
        lines.append("    " + c_bytes(js.encode()) + ",")
    lines.append("};")
    lines.append("typedef struct { uint32_t v; uint32_t flags; uint32_t n; uint32_t ids[12]; const char *want; uint32_t want_len; } dec_case;")
    lines.append("static const dec_case DEC_CASES[] = {")
    n_cases = 0
    for vi, js in enumerate(jsons):
        tk = Tokenizer.from_str(js)
        n_ids = tk.get_vocab_size(with_added_tokens=True)
        for k in range(250):
            n = rng.randint(1, 12)
            ids = [rng.randrange(n_ids) for _ in range(n)]
            for fl in (0, 1):
                s = tk.decode(ids, skip_special_tokens=bool(fl)).encode("utf-8")
                lines.append("    { %d, %d, %d, { %s }, %s, %d }," % (vi, fl, n, ", ".join(map(str, ids)), c_bytes(s), len(s)))
                n_cases += 1
    lines.append("};")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT, n_cases, "cases over", len(jsons), "tokenizers")


if __name__ == "__main__":
    main()
