/*
 * test_k3_dsv3.c: hand cases for the dsv3 K3 c twin (docs/templates/dsv3.md, kernels.md §2-3): every rule and
 * every note with hf's pieces (tests/k3/dsv3_golden.h; ill-formed utf-8 with the python model's pieces), the
 * TOKS_CLASSES_DSV3 class tables against the doc's §2 (every code point), all strings of up to 3 atoms over a
 * representative alphabet and of 4 atoms over a smaller one (ill-formed bytes among the atoms), ill-formed bytes
 * at every position, long runs of every kind, caps 1..n with resume equivalence, guard-page geometry (no read
 * at or past len; lengths 0..255, start alignment 0..63), the parameter bits the template ignores, and the abi
 * (callee-saved registers) through toks_abicheck_call.
 *
 * Two oracles: hf 0.23.2's pieces for the golden cases (generated by tests/k3/dsv3_gen.py golden), and a
 * reference scanner restating the doc's rules over a decoded atom array (written from the prose, not from the
 * kernel's streaming code) for everything else. The outer oracle at scale is tests/k3/dsv3_run.sh on a lab host;
 * this file is the fast gate.
 */
/* kernels.h -> core.h redeclares memcpy/memset/memcmp (freestanding core): it must come before <string.h>. */
#include "../../src/core/classes.h"
#include "../../src/core/compile.h"
#include "../../src/core/kernels.h"
#include "../../src/core/layout.h"
#include "../../src/gen/ucd_flags.h"
#include "../common/guard.h"

/* the tier under test: the c twin by default; for an asm tier, build this file with -DK3_SCAN=toks_k3_scan_dsv3_<tier> */
#ifndef K3_SCAN
#define K3_SCAN toks_k3_scan_dsv3_c
#endif
uint64_t K3_SCAN(const toks_tables *t, toks_k3_args *a);
/* the tier's whole kernel: an asm part runs with the c twin's stretches (kernels.h toks_k3_tier) */
static uint64_t k3_scan(const toks_tables *t, toks_k3_args *a)
{
    return toks_k3_tier(K3_SCAN, toks_k3_scan_dsv3_c, t, a);
}

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { uint8_t hf; const char *s; uint32_t len, first, n; } golden_case;
#include "../k3/dsv3_golden.h"

/* ---------------------------------------------------------------- tables */

static uint8_t cls_buf[128 + 2 * 0x1100 + 0x1100 * 256];
static toks_class_tables CT;
static toks_tables TT;

static void build_tables(void)
{
    if (toks_classes_build(TOKS_CLASSES_DSV3, cls_buf, sizeof cls_buf, &CT) <= 0) {
        fprintf(stderr, "classes build (TOKS_CLASSES_DSV3) failed\n");
        exit(2);
    }
    memset(&TT, 0, sizeof TT);
    TT.magic = TOKS_TABLES_MAGIC;
    TT.version = TOKS_TABLES_VERSION;
    TT.tmpl = TOKS_TMPL_DSV3;
    TT.tmpl_params = 0u;
    TT.cls_ascii = CT.ascii;
    TT.cls_stage1 = CT.stage1;
    TT.cls_stage2 = CT.stage2;
    TT.cls_nblocks = CT.n_blocks;
    TT.flags = (uint32_t)toks_compile_cls_flags(&TT);  /* TOKS_TF_CJK_D, as the compiler sets it */
}

/* ---------------------------------------------------------------- the reference scanner */

#define MAXCASE 40000
#define NONE (-1)
enum { P = TOKS_C_P, L = TOKS_C_L, N = TOKS_C_N, WS = TOKS_C_WS, NL = TOKS_C_NL, X = TOKS_C_X, CJK = TOKS_C_CJK };

typedef struct { uint32_t off, cp; uint8_t kind, ascii; } ratom;
static ratom RA[MAXCASE + 1];
static int M;                                         /* atoms in RA */

/* kernels.md §2: a well-formed sequence is one atom; any other byte a one-byte atom of kind P */
static void decode(const uint8_t *text, uint64_t len)
{
    uint64_t i = 0;
    M = 0;
    while (i < len) {                                 /* bound: len (>= 1 byte per atom) */
        uint32_t k = toks_utf8_len(text + i, len - i);
        ratom a;
        a.off = (uint32_t)i;
        a.ascii = 0u;
        if (k == 0u) { a.cp = text[i]; a.kind = P; k = 1u; }
        else if (k == 1u) { a.cp = text[i]; a.kind = CT.ascii[text[i]]; a.ascii = 1u; }
        else { a.cp = toks_cp_decode(text + i, k); a.kind = toks_class_of(&CT, a.cp); }
        RA[M++] = a;
        i += k;
    }
    RA[M].off = (uint32_t)len;
}

static int base(int j) { return j < M ? (RA[j].kind & 7) : -1; }                   /* absent: no class */
static int inreg(int j, int want, int r) { return j < M && RA[j].kind == (want | r); }
static int run(int j, int want, int r) { while (inreg(j, want, r)) { j++; } return j; }   /* bound: M */
static int ascii_of(int j, int b) { return j < M && RA[j].ascii && base(j) == b; }

static uint64_t ref_scan(const uint8_t *text, uint64_t len, uint64_t cap, uint32_t *ends)
{
    uint64_t n = 0;
    int i = 0;
    decode(text, len);
    while (i < M && n < cap) {                        /* bound: M pieces at most */
        int c = RA[i].kind, b = c & 7, r = c & CJK, e = NONE;
        if (b == N) {                                                          /* D0 */
            e = i + 1;
            while (e < M && e < i + 3 && base(e) == N) { e++; }
        } else if (ascii_of(i, P) && ascii_of(i + 1, L)) {                      /* D1 */
            e = i + 1;
            while (ascii_of(e, L)) { e++; }
        } else if (b == L) {                                                   /* D2 */
            e = run(i, L, r);
        } else if ((b == WS || b == X) && inreg(i + 1, L, r)) {
            e = run(i + 1, L, r);
        }
        if (e == NONE) {                                                       /* D3 */
            int j = b == P ? i : (RA[i].cp == 0x20u && inreg(i + 1, P, r) ? i + 1 : NONE);
            if (j != NONE) { e = run(run(j, P, r), NL, r); }
        }
        if (e == NONE && (b == WS || b == NL)) {                               /* D4-D6 */
            int k = i, t;
            while (base(k) == WS || base(k) == NL) { k++; }                    /* bound: M */
            for (t = k - 1; t >= i && base(t) != NL; t--) { }                  /* bound: k - i */
            int region_end = k == M || base(k) == N || (RA[k].kind & CJK) != r;
            if (t >= i) { e = t + 1; }
            else if (region_end) { e = k; }
            else if (k - i >= 2) { e = k - 1; }
            else { e = k; }
        }
        if (e == NONE) {                                                       /* D7: b is X */
            int g = run(i, X, r);
            e = inreg(g, L, r) ? g - 1 : g;
        }
        ends[n++] = RA[e].off;
        i = e;
    }
    return n;
}

/* ---------------------------------------------------------------- harness */

static int failures;
static uint64_t checks;

static void dump(const char *what, const uint32_t *e, uint64_t n)
{
    fprintf(stderr, "  %s:", what);
    for (uint64_t i = 0; i < n && i < 40u; i++) { fprintf(stderr, " %" PRIu32, e[i]); }
    fprintf(stderr, n > 40u ? " ...\n" : "\n");
}

static void fail_text(const char *label, const uint8_t *text, uint64_t len)
{
    fprintf(stderr, "FAIL %s: text", label);
    for (uint64_t i = 0; i < len && i < 48u; i++) { fprintf(stderr, " %02X", text[i]); }
    fprintf(stderr, "\n");
}

/* kernel == expected (or the ref when expected is NULL); contract; resume with caps 1..maxcap */
static void run_case(const char *label, const uint8_t *text, uint64_t len, const uint32_t *expect, uint64_t en,
                     uint64_t maxcap)
{
    static uint32_t want[MAXCASE], got[MAXCASE], acc[MAXCASE];
    uint64_t rn = ref_scan(text, len, MAXCASE, want);
    if (expect != NULL) {                             /* the ref must reproduce hf / the model */
        if (rn != en || memcmp(want, expect, (size_t)en * 4u) != 0) {
            if (failures < 20) { fail_text(label, text, len); dump("expect", expect, en); dump("ref", want, rn); }
            failures++;
            return;
        }
    }
    toks_k3_args a;
    memset(&a, 0, sizeof a);
    a.text = text; a.len = len; a.pos = 0; a.ends = got; a.cap = MAXCASE;
    uint64_t kn = k3_scan(&TT, &a);
    checks++;
    if (kn != rn || memcmp(want, got, (size_t)rn * 4u) != 0 || a.n != kn) {
        if (failures < 20) { fail_text(label, text, len); dump("want", want, rn); dump("got", got, kn); }
        failures++;
        return;
    }
    uint64_t prev = 0;                                /* ends strictly increase in (pos, len] */
    for (uint64_t i = 0; i < rn; i++) {
        if (got[i] <= prev || got[i] > len) {
            if (failures < 20) { fail_text(label, text, len); fprintf(stderr, "  end out of order\n"); }
            failures++;
            return;
        }
        prev = got[i];
    }
    if ((rn != 0u && (a.pos != got[rn - 1u] || got[rn - 1u] != len)) || (rn == 0u && (a.pos != 0u || len != 0u))) {
        if (failures < 20) { fail_text(label, text, len); fprintf(stderr, "  pos %" PRIu64 "\n", a.pos); }
        failures++;
        return;
    }
    if (maxcap > rn + 1u) { maxcap = rn + 1u; }
    for (uint64_t cap = 1; cap <= maxcap; cap++) {    /* resume: every cap tiles to the same pieces */
        uint64_t pos = 0, an = 0;
        while (pos < len) {                           /* bound: pieces (each call advances >= 1) */
            memset(&a, 0, sizeof a);
            a.text = text; a.len = len; a.pos = pos; a.ends = acc + an; a.cap = cap;
            uint64_t c = k3_scan(&TT, &a);
            if (c == 0u || c > cap || a.pos <= pos || a.n != c || an + c > MAXCASE) {
                if (failures < 20) { fail_text(label, text, len); fprintf(stderr, "  cap %" PRIu64 " stalls\n", cap); }
                failures++;
                return;
            }
            an += c;
            pos = a.pos;
        }
        if (an != rn || memcmp(acc, want, (size_t)rn * 4u) != 0) {
            if (failures < 20) { fail_text(label, text, len); fprintf(stderr, "  resume cap %" PRIu64 "\n", cap); }
            failures++;
            return;
        }
        checks++;
    }
}

static uint64_t utf8(uint32_t cp, uint8_t *o)
{
    if (cp < 0x80u) { o[0] = (uint8_t)cp; return 1; }
    if (cp < 0x800u) { o[0] = (uint8_t)(0xC0u | (cp >> 6)); o[1] = (uint8_t)(0x80u | (cp & 0x3Fu)); return 2; }
    if (cp < 0x10000u) {
        o[0] = (uint8_t)(0xE0u | (cp >> 12)); o[1] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        o[2] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 3;
    }
    o[0] = (uint8_t)(0xF0u | (cp >> 18)); o[1] = (uint8_t)(0x80u | ((cp >> 12) & 0x3Fu));
    o[2] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu)); o[3] = (uint8_t)(0x80u | (cp & 0x3Fu));
    return 4;
}

/* ---------------------------------------------------------------- the class tables (docs/templates/dsv3.md §2) */

static void check_classes(void)
{
    /* the ascii kinds, by hand */
    for (uint32_t b = 0; b < 0x80u; b++) {            /* bound: 128 */
        uint8_t want;
        if (b == 0x0Au || b == 0x0Du) { want = NL; }
        else if (b == 0x09u || b == 0x0Bu || b == 0x0Cu || b == 0x20u) { want = WS; }
        else if (b < 0x20u || b == 0x7Fu) { want = X; }
        else if (b >= 0x30u && b <= 0x39u) { want = N; }
        else if ((b >= 0x41u && b <= 0x5Au) || (b >= 0x61u && b <= 0x7Au)) { want = L; }
        else { want = P; }
        checks++;
        if (CT.ascii[b] != want || toks_class_of(&CT, b) != want) {
            fprintf(stderr, "FAIL classes: ascii %02X is %#x, want %#x\n", b, CT.ascii[b], want);
            failures++;
        }
    }
    /* every code point: base | CJK only, base <= X, CJK exactly on the two ranges, the base from the generated
     * onig flags as §2 says; and the kind counts the onig probes gave (tests/model/dsv3_model.py) */
    static const struct { uint8_t kind; uint32_t count; } COUNTS[] = {
        { P, 9365u }, { L, 122442u }, { N, 1911u }, { WS, 23u }, { NL, 2u }, { X, 957227u + 2048u },
        { P | CJK, 4u }, { L | CJK, 21087u }, { X | CJK, 3u },
    };
    uint32_t count[256];
    uint32_t bad = 0u;
    memset(count, 0, sizeof count);
    for (uint32_t cp = 0; cp <= 0x10FFFFu; cp++) {    /* bound: every code point */
        uint8_t k = toks_class_of(&CT, cp);
        uint16_t f = toks_ucd_flags(cp);
        int cjk = (cp >= 0x3040u && cp <= 0x30FFu) || (cp >= 0x4E00u && cp <= 0x9FA5u);
        uint8_t want = (f & (TOKS_UCD_LETTERS | TOKS_UCD_M)) != 0 ? L
                     : (f & TOKS_UCD_N) != 0 ? N
                     : (cp == 0x0Au || cp == 0x0Du) ? NL
                     : (f & TOKS_UCD_WS) != 0 ? WS
                     : (f & (TOKS_UCD_P | TOKS_UCD_S)) != 0 ? P : X;
        want = (uint8_t)(want | (cjk ? CJK : 0));
        count[k]++;
        if (k != want) {
            if (bad < 8u) { fprintf(stderr, "FAIL classes: U+%04X is %#x, want %#x\n", cp, k, want); }
            bad++;
        }
    }
    checks += 0x110000u;
    failures += (int)bad;
    for (size_t i = 0; i < sizeof COUNTS / sizeof COUNTS[0]; i++) {   /* bound: 9 kinds */
        checks++;
        if (count[COUNTS[i].kind] != COUNTS[i].count) {
            fprintf(stderr, "FAIL classes: kind %#x on %u code points, want %u\n", COUNTS[i].kind,
                    count[COUNTS[i].kind], COUNTS[i].count);
            failures++;
        }
    }
    /* spot values the doc names */
    static const struct { uint32_t cp; uint8_t kind; } SPOT[] = {
        { 0x85u, WS }, { 0xA0u, WS }, { 0xADu, X }, { 0xABu, P }, { 0xBDu, N }, { 0x301u, L }, { 0x200Bu, X },
        { 0x200Du, X }, { 0x2028u, WS }, { 0x3000u, WS }, { 0x3005u, L }, { 0x3006u, L }, { 0x3007u, N },
        { 0x3040u, X | CJK }, { 0x3041u, L | CJK }, { 0x3097u, X | CJK }, { 0x3098u, X | CJK },
        { 0x3099u, L | CJK }, { 0x309Bu, P | CJK }, { 0x309Cu, P | CJK }, { 0x309Fu, L | CJK },
        { 0x30A0u, P | CJK }, { 0x30FBu, P | CJK }, { 0x30FCu, L | CJK }, { 0x30FFu, L | CJK }, { 0x3100u, X },
        { 0x4DFFu, P }, { 0x4E00u, L | CJK }, { 0x9FA5u, L | CJK }, { 0x9FA6u, L }, { 0xE000u, X },
        { 0xFE0Fu, L }, { 0xFEFFu, X }, { 0xFF04u, P }, { 0x1F600u, P }, { 0xE0001u, X }, { 0x10FFFFu, X },
        { 0xF0000u, X }, { 0x378u, X }, { 0x2764u, P }, { 0x1F3FBu, P },
    };
    for (size_t i = 0; i < sizeof SPOT / sizeof SPOT[0]; i++) {       /* bound: the table */
        checks++;
        if (toks_class_of(&CT, SPOT[i].cp) != SPOT[i].kind) {
            fprintf(stderr, "FAIL classes: U+%04X is %#x, want %#x\n", SPOT[i].cp, toks_class_of(&CT, SPOT[i].cp),
                    SPOT[i].kind);
            failures++;
        }
    }
    /* every other build is unchanged by the dsv3 flag: no X base and no bit 7 */
    static uint8_t buf2[128 + 2 * 0x1100 + 0x1100 * 256];
    toks_class_tables o;
    for (uint32_t fl = 0; fl < 2u; fl++) {            /* bound: 2 builds */
        uint32_t odd = 0u;
        if (toks_classes_build(fl, buf2, sizeof buf2, &o) <= 0) { fprintf(stderr, "classes build failed\n"); exit(2); }
        for (uint32_t cp = 0; cp <= 0x10FFFFu; cp++) {             /* bound: every code point */
            uint8_t k = toks_class_of(&o, cp);
            odd += ((k & 7u) > NL || (k & 0x80u) != 0u) ? 1u : 0u;
        }
        checks++;
        if (odd != 0u) { fprintf(stderr, "FAIL classes: flags %u build has %u dsv3-only kinds\n", fl, odd); failures++; }
    }
    checks += 3u;
    if (toks_classes_bytes(TOKS_CLASSES_DSV3) != sizeof cls_buf ||
        toks_classes_bytes(TOKS_CLASSES_DSV3 | TOKS_CLASSES_MARKS_ARE_LETTERS) != sizeof cls_buf) {
        fprintf(stderr, "FAIL classes: bytes for the dsv3 flag\n");
        failures++;
    }
    if (toks_classes_bytes(0x10u) != 0u || toks_classes_build(0x10u, buf2, sizeof buf2, &o) != TOKS_CLASSES_E_FLAGS) {
        fprintf(stderr, "FAIL classes: an unknown class_flags bit is accepted\n");
        failures++;
    }
    {   /* MARKS_ARE_LETTERS changes nothing under DSV3 (marks are letters there already) */
        toks_class_tables m;
        uint32_t diff = 0u;
        if (toks_classes_build(TOKS_CLASSES_DSV3 | TOKS_CLASSES_MARKS_ARE_LETTERS, buf2, sizeof buf2, &m) <= 0) {
            fprintf(stderr, "classes build failed\n");
            exit(2);
        }
        for (uint32_t cp = 0; cp <= 0x10FFFFu; cp++) { diff += toks_class_of(&m, cp) != toks_class_of(&CT, cp); }
        if (diff != 0u) { fprintf(stderr, "FAIL classes: DSV3 | MARKS_ARE_LETTERS differs on %u\n", diff); failures++; }
    }
}

/* ---------------------------------------------------------------- cases */

int main(void)
{
    build_tables();
    check_classes();

    /* the golden cases: hf 0.23.2's pieces for every rule and note of docs/templates/dsv3.md (hf = 1), the
     * python model's for ill-formed utf-8 (hf = 0); each also through the abi checker */
    for (size_t g = 0; g < sizeof GOLDEN / sizeof GOLDEN[0]; g++) {   /* bound: the table */
        char label[48];
        snprintf(label, sizeof label, "golden #%zu%s", g, GOLDEN[g].hf ? "" : " (ill-formed)");
        run_case(label, (const uint8_t *)GOLDEN[g].s, GOLDEN[g].len, GOLDEN_ENDS + GOLDEN[g].first, GOLDEN[g].n,
                 MAXCASE);
        static uint32_t e[64];
        toks_k3_args a;
        uint64_t report = 0;
        memset(&a, 0, sizeof a);
        a.text = (const uint8_t *)GOLDEN[g].s; a.len = GOLDEN[g].len; a.ends = e; a.cap = 64;
        (void)toks_abicheck_call((const void *)K3_SCAN, (uint64_t)(uintptr_t)&TT, (uint64_t)(uintptr_t)&a, &report);
        checks++;
        if (report != 0u) { fprintf(stderr, "FAIL %s: callee-saved registers clobbered (%#" PRIx64 ")\n", label, report); failures++; }
    }

    /* every string of 0..3 atoms over one representative per behaviour (two ill-formed ones among them), and of
     * exactly 4 atoms over a smaller set */
    {
        static const char *const rep[] = {
            "a", "Z", "\xC3\xA9", "\xCC\x81", "\xE4\xB8\xAD", "\xE3\x82\xAB", "\xE3\x82\x99", "\xE3\x83\xBB",
            "\xE3\x82\x9B", "\xE3\x81\x80", "1", "\xD9\xA3", " ", "\t", "\xE3\x80\x80", "\xC2\xA0", "\r", "\n", "!",
            "'", "\xC2\xAB", "\xF0\x9F\x98\x80", "\x00", "\xC2\xAD", "\xEE\x80\x80", "\xE2\x80\xA8", ".", "\xFF",
            "\xE3\x81"
        };
        static const uint32_t replen[] = { 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 1, 2, 1, 1, 3, 2, 1, 1, 1, 1, 2, 4, 1, 2, 3,
                                           3, 1, 1, 2 };
        static const char *const small[] = { "a", "\xCC\x81", "\xE4\xB8\xAD", "\xE3\x83\xBB", "\xE3\x81\x80", "1", " ",
                                             "\n", "!", "\xC2\xAB", "\x00", "\xE3\x80\x80", "\xFF" };
        static const uint32_t smalllen[] = { 1, 2, 3, 3, 3, 1, 1, 1, 1, 2, 1, 3, 1 };
        const size_t nr = sizeof replen / sizeof replen[0], ns = sizeof smalllen / sizeof smalllen[0];
        uint8_t buf[32];
        for (size_t x = 0; x < nr * nr * nr + nr * nr + nr + 1u; x++) {   /* bound: 29^3 + 29^2 + 29 + 1 */
            size_t na = x == 0u ? 0u : x <= nr ? 1u : x <= nr + nr * nr ? 2u : 3u;
            size_t idx = x == 0u ? 0u : na == 1u ? x - 1u : na == 2u ? x - 1u - nr : x - 1u - nr - nr * nr;
            uint64_t n = 0;
            for (size_t k = 0; k < na; k++) { memcpy(buf + n, rep[idx % nr], replen[idx % nr]); n += replen[idx % nr]; idx /= nr; }
            run_case("rep<=3", buf, n, NULL, 0, 4);
        }
        for (size_t x = 0; x < ns * ns * ns * ns; x++) {                  /* bound: 13^4 */
            size_t idx = x;
            uint64_t n = 0;
            for (int k = 0; k < 4; k++) { memcpy(buf + n, small[idx % ns], smalllen[idx % ns]); n += smalllen[idx % ns]; idx /= ns; }
            run_case("small4", buf, n, NULL, 0, 5);
        }
    }

    /* ill-formed utf-8: every kind at every position (kernel == ref) */
    {
        static const uint8_t salad[] = {
            'a', 0xC3, 0xA9, 'B', 0xE0, 0x80, 0x80, 'c',              /* overlong E0 80 80 */
            0xF0, 0x9F, 0x98, 'd',                                     /* truncated 4-byte */
            0x80, 0xE4, 0xB8, 0xAD,                                    /* lone continuation, then a CJK atom */
            0xC2, '1', '\'', 0xE3, 0x82,                               /* C2 then a digit; ' then a cut kana */
            0xED, 0xA0, 0x80, 'g',                                     /* encoded surrogate */
            0xF4, 0x90, 0x80, 0x80, ' ',                               /* above U+10FFFF */
            0xC0, 0xAF, '!', '\n', 0xFF,                               /* overlong 2-byte, a tail, FF */
            0xE0, 0x9F, 0xBF, 0xCC, 0x81, 0xE3, 0x81, 0x80,            /* E0 out of range, a mark, U+3040 */
            0xF0, 0x80, 0x80, 0x80, 0xE3, 0x83, 0xBB, 0x00, 0x00, 'z'  /* overlong 4-byte, U+30FB, NULs */
        };
        run_case("utf8 salad", salad, sizeof salad, NULL, 0, MAXCASE);
        for (uint64_t cut = 0; cut <= sizeof salad; cut++) {   /* bound: salad length */
            run_case("salad cut", salad, cut, NULL, 0, 3);
            run_case("salad tail", salad + cut, sizeof salad - cut, NULL, 0, 3);
        }
        for (int x = 0x80; x < 0x100; x++) {                     /* bound: 128 bad bytes */
            const uint8_t ctx[][4] = {
                { 'a', (uint8_t)x, 'b', 0 }, { '!', (uint8_t)x, 'a', 0 }, { (uint8_t)x, 0xCC, 0x81, 0 },
                { ' ', (uint8_t)x, '\n', 0 }, { (uint8_t)x, 'a', 'b', 0 }, { 0x00, (uint8_t)x, 'a', 0 },
                { '1', (uint8_t)x, '2', 0 }, { (uint8_t)x, 0, 0, 0 }, { (uint8_t)x, 0xE4, 0xB8, 0xAD }
            };
            const uint64_t ctxlen[] = { 3, 3, 3, 3, 3, 3, 3, 1, 4 };
            for (size_t c = 0; c < sizeof ctxlen / sizeof ctxlen[0]; c++) {   /* bound: 9 contexts */
                run_case("bad byte", ctx[c], ctxlen[c], NULL, 0, 4);
            }
        }
    }

    /* long runs of every kind (one piece each, or chunks of 3 for N; whitespace gives back one atom before L) */
    {
        static uint8_t big[30000];
        static const uint32_t cps[] = { 'a', 0x4E2D, '7', ' ', '\n', '!', 0x00, 0x3040, 0x30FB, 0xE9, 0x301, 0xFF01 };
        for (size_t c = 0; c < sizeof cps / sizeof cps[0]; c++) {          /* bound: 12 kinds */
            uint64_t n = 0;
            uint8_t u[4];
            uint64_t k = utf8(cps[c], u);
            while (n + k + 1u <= sizeof big - 1u) { memcpy(big + n, u, k); n += k; }   /* bound: sizeof big */
            big[n++] = 'x';                                                  /* a letter after the run */
            run_case("long run", big, n, NULL, 0, 3);
            run_case("long run, no tail", big, n - 1u, NULL, 0, 3);
        }
    }

    /* the template ignores every tmpl_params bit (docs/templates/dsv3.md §1) */
    {
        static const char soup[] = "Hello, world! It's 2024.\nDON'T 12345 \xE6\x97\xA5\xE6\x9C\xAC\xE8\xAA\x9E\xE3\x83\xBB"
                                   "\xE3\x82\xAB\xE3\x81\x80 \x00\x00x \xC2\xAB!\n\n  \xF0\x9F\x98\x80 .com";
        static uint32_t e0[256], e1[256];
        const uint64_t len = sizeof soup - 1u;
        toks_tables t2 = TT;
        toks_k3_args a;
        memset(&a, 0, sizeof a);
        a.text = (const uint8_t *)soup; a.len = len; a.ends = e0; a.cap = 256;
        uint64_t n0 = k3_scan(&TT, &a);
        t2.tmpl_params = 0xFFFFFFFFu;
        memset(&a, 0, sizeof a);
        a.text = (const uint8_t *)soup; a.len = len; a.ends = e1; a.cap = 256;
        uint64_t n1 = k3_scan(&t2, &a);
        checks++;
        if (n0 != n1 || memcmp(e0, e1, (size_t)n0 * 4u) != 0) {
            fprintf(stderr, "FAIL: ignored parameter bits change the pieces\n");
            failures++;
        }
        run_case("soup", (const uint8_t *)soup, len, NULL, 0, 8);
    }

    /* guard-page geometry: deterministic text, lengths 0..255, end flush against a no-access page and start right
     * after one at every alignment 0..63 (kernels.md §1; SPEC §14.3); the pool ends in cut sequences */
    {
        uint64_t seed = 0x44535633ull;
        static const uint8_t pool[] =
            "aZs!.' \t\r\n1\x00\xC3\xA9\xCC\x81\xE4\xB8\xAD\xE3\x82\xAB\xE3\x83\xBB\xE3\x81\x80\xE3\x82\x9B\xC2\xA0"
            "\xE3\x80\x80\xC2\xAB\xD9\xA3\xF0\x9F\x98\x80\xC2\xAD\x80\xFF\xE3\x81\xE4\xB8\xF0\x9F";
        uint8_t buf[256];
        for (uint64_t len = 0; len <= 255; len++) {            /* bound: 256 lengths */
            for (uint64_t i = 0; i < len; i++) {               /* bound: len */
                buf[i] = pool[guard_rng(&seed) % (sizeof pool - 1u)];
            }
            for (int where = 0; where < 2; where++) {           /* bound: 2 guard kinds */
                for (size_t off = 0; off < (where == GUARD_START ? 64u : 1u); off++) {   /* bound: 64 */
                    guard_buf g = { 0 };
                    uint8_t *p = guard_alloc(&g, (size_t)len, where, off);
                    if (!p) { fprintf(stderr, "guard_alloc failed\n"); return 2; }
                    memcpy(p, buf, (size_t)len);
                    uint64_t mc = (where == GUARD_END || off == 0u) ? MAXCASE : 1u;
                    run_case("guard", p, len, NULL, 0, mc);
                    guard_free(&g);
                }
            }
        }
    }

    printf("test_k3_dsv3: %" PRIu64 " checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
