#!/usr/bin/env python3
"""tests/c/test_kimi.py: writes test_kimi.inc next to it, what test_kimi.c checks toks against for Kimi K3.

    uv run --python 3.12 --with tiktoken==0.14.0 --with transformers==5.18.0 python tests/c/test_kimi.py

The reference is tests/parity/oracle_tiktoken.py (the model's own TikTokenTokenizer through transformers,
pinned files and versions; docs/models/kimi.md): toks ALL = serving, NONSPECIAL = direct, NONE = none, and
decode(serving ids) with and without skip_special_tokens. Each text is a recipe of (string, repeat) parts, so
the 25,000-run and 400,000-chunk edges cost a few lines here; each expectation is the count and the sha-256 of
the ids (u32 little-endian) or of the decoded utf-8.
"""
from __future__ import annotations

import hashlib
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "parity"))

import oracle_tiktoken  # noqa: E402

R = [
    # docs/models/kimi.md §5 notes and the self-check text
    [("", 1)],
    [("Hello world! \u4f60\u597d\u4e16\u754c [BOS] <|open|>x<|reserved_token_163600|> done", 1)],
    [(" \u4e2d\u6587 \u3000\u4e2d \u2e80x \u4e2d\u2e80 !\u2e80 1\u3007\u3007\u3007 x\u3005y \u3005x A\u4e2dB \u4e2dA's", 1)],
    [("\ud55c\uad6dABC ABC\ud55c\uad6dDEF \u3042\u3044\u4e2d\u3046 \u30ab\u30bf\u30ab\u30ca\u30fc\u4e2d "
      "\u4e2d\u6587\u5b57\u3002\u65e5\u672c\u8a9e\u3067\u3059 \uff10\uff11\uff12\uff13 !\n/x \x1c\x1c a", 1)],
    [("\u0301A! !\u0301 !!\u0301 'llama 1's don't it'\u017f camelCase HTMLParser \u3001x a\u3001b", 1)],
    [("[EOS]<|end_of_msg|>[start_header_id]user[end_header_id]\nhi <|close|><|sep|>[EOT]<|media_pad|> "
      "<|reserved_token_163837|>[BOS[UNK]<|im_end|>", 1)],
    # the 25,000 cuts: a name straddling one (direct cuts it; serving's trie takes it first), a non-trie name
    [("a", 24998), ("[BOS]", 1), ("b", 10)],
    [("a", 24990), ("[BOS]", 1), ("b", 10)],
    [("a", 25000), ("[BOS]", 1), ("b", 10)],
    [("a", 20000), ("[BOS]", 1), ("b", 10000)],
    [("a", 24998), ("<|reserved_token_163600|>", 1), ("c", 1)],
    [("\u4e2d", 24999), ("<|open|>", 1), ("\u6587", 3)],
    # the walk's skip (api.c run_cuts): <= 25,000 bytes hold no cut; 25,001 one-byte chars of one class hold one
    [("a", 24975), ("<|reserved_token_163600|>", 1)],   # 25,000 bytes: the name whole in serving and direct
    [("a", 24976), ("<|reserved_token_163600|>", 1)],   # 25,001: cut before its '>' (no trie name: serving too)
    [("a", 24995), ("[BOS]", 1)],                       # 25,000 bytes: direct recognizes [BOS]
    [("a", 24996), ("[BOS]", 1)],                       # 25,001: direct cuts before its ']'
    # runs of one str.isspace() class: past 25,000, 50,000; U+001C is whitespace for the cuts, P for the pattern
    [("x", 1), (" ", 25001), ("y", 1)],
    [("\x1c", 25001), ("a", 1)],
    [("\u4e2d", 25001)],
    [("\u3000", 50001), ("z", 1)],
    [("\n", 25000), ("\t", 2), ("q", 1)],
    [("ab", 12500), ("c", 1), (" ", 3), ("d", 25002)],
    [("a", 20000), ("\x1c", 1), ("a", 10000)],        # U+001C breaks the non-space run: no cut (\s would cut)
    [(" ", 20000), ("\x1d", 1), (" ", 10000), ("b", 1)],   # U+001D continues the space run: a cut at 25,000
    # the 400,000-code-point chunks: short runs only, a name straddling the edge, a trie gap restarting the count
    [("ab ", 140000)],
    [("ab ", 133333), ("[BOS]", 1), ("x", 1)],
    [("x", 399999), ("<|open|>", 1), ("y", 1)],
    [("\u4e2d\u6587 ", 133334), ("<|reserved_token_163650|>", 1), ("!", 1)],
    [("ab ", 133330), ("a", 30010)],                  # a run across the chunk edge: the count restarts there
]

MODES = (("serving", 0), ("direct", 1), ("none", 2))


def c_bytes(b: bytes) -> str:
    out = []
    for x in b:
        out.append(chr(x) if 0x20 <= x < 0x7F and x not in (0x22, 0x5C, 0x3F) else f"\\{x:03o}")
    return '"' + "".join(out) + '"'


def sha_ids(ids) -> str:
    return hashlib.sha256(b"".join(struct.pack("<I", i) for i in ids)).hexdigest()


def main():
    k = oracle_tiktoken.Kimi()
    parts, cases, enc, dec = [], [], [], []
    for r in R:
        cases.append((len(parts), len(r)))
        parts += r
        text = "".join(s * n for s, n in r)
        sv = None
        for name, _fl in MODES:
            ids = k.encode(text, name)
            if name == "serving":
                sv = ids
            enc.append((len(ids), sha_ids(ids)))
        for skip in (False, True):
            d = k.decode(sv, skip).encode("utf-8")
            dec.append((len(d), hashlib.sha256(d).hexdigest()))
    out = ["/* generated by tests/c/test_kimi.py from tests/parity/oracle_tiktoken.py (tiktoken 0.14.0, transformers",
           " * 5.18.0, moonshotai/Kimi-K3 @ " + oracle_tiktoken.KIMI_REVISION[:12] + "); do not edit */",
           "static const struct { const char *s; uint32_t len, rep; } KP[] = {"]
    for s, n in parts:
        b = s.encode("utf-8")
        out.append(f"    {{ {c_bytes(b)}, {len(b)}u, {n}u }},")
    out.append("};")
    out.append("static const struct { uint32_t first, n; } KC[] = {")
    out += [f"    {{ {a}u, {b}u }}," for a, b in cases]
    out.append("};")
    out.append(f"#define KIMI_N {len(cases)}")
    out.append("/* per case: serving (ALL), direct (NONSPECIAL), none (NONE): id count, sha-256 of the ids (u32 LE) */")
    out.append("static const struct { uint32_t n; const char *sha; } KE[] = {")
    out += [f'    {{ {n}u, "{h}" }},' for n, h in enc]
    out.append("};")
    out.append("/* per case: decode(serving ids), skip_special_tokens false / true: byte count, sha-256 of the utf-8 */")
    out.append("static const struct { uint32_t n; const char *sha; } KD[] = {")
    out += [f'    {{ {n}u, "{h}" }},' for n, h in dec]
    out.append("};")
    dst = os.path.join(HERE, "test_kimi.inc")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {dst}: {len(cases)} texts, {len(enc)} encode and {len(dec)} decode expectations")


if __name__ == "__main__":
    main()
