#!/usr/bin/env python3
"""tests/c/test_wp_e2e.py: writes test_wp_e2e.inc next to it, the ids and piece ends test_wp_e2e.c checks toks
against on six pinned WordPiece tokenizers (feature-distinct: truncation + Fixed padding, BatchLongest, Roberta
post-processing with a normalized <unk> and an lstrip <mask>, cased chinese, cased multilingual, no truncation).

    uv run --with tokenizers==0.23.2 python tests/c/test_wp_e2e.py

hf tokenizers 0.23.2 is the definition (python/toks_oracle: mode ALL = hf default, NONSPECIAL =
encode_special_tokens=True, NONE = the file with added_tokens removed; flag 4 = add_special_tokens=False; pieces =
end offsets in the normalized stream). The files are tests/wordpiece/pins.json's under $TOKS_TOKENIZER_CACHE or
~/.cache/toks/tokenizers (wp-<name>). A trailing run of the pin's pad id is stored as a count.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "python"))

from toks_oracle import oracle as O  # noqa: E402

ROOT = os.environ.get("TOKS_TOKENIZER_CACHE", os.path.expanduser("~/.cache/toks/tokenizers"))
PINS = ["minilm-l6", "mpnet", "ko-sroberta", "bge-small-zh", "distiluse-ml", "bert-uncased"]

MULTI = ("Ελληνικά κείμενα, Русский текст; العربية والفارسية. हिन्दी में लिखा। 日本語のテキストと中文文本。"
         "한국어 문장입니다. ภาษาไทยไม่มีช่องว่าง Türkçe İstanbul ıi, Français: déjà vu, naïve café. ")
TEXTS = [
    "",
    "Hello world",
    "Hello, World! How's it going? I'm fine; we'll see.",
    "Caf\u00e9 na\u00efve \u00c5ngstr\u00f6m \u00dcber stra\u00dfe \u00c9COLE",
    "\u65e5\u672c\u8a9e\u306e\u30c6\u30ad\u30b9\u30c8\u3001\u4e2d\u6587\u6587\u672c\u3002\ud55c\uad6d\uc5b4 \U00020000\U0002A700",
    "[CLS] hello [SEP] [MASK] x [PAD] [UNK] [cls]",
    "a <mask> b  <mask>c <unk> <UNK> \u226eunk> <s></s> <pad>",
    "tabs\tand\u00a0nbsp \u3000 x\u2028y \u0085z \x0b\x0c\x00\x01 \ufffd end",
    " ".join(["unbelievably tokenization"] * 120),
    "x\u200by soft\u00adhyphen e\u0301 \u0130stanbul \u212a \u00df \u1e9e",
    "emoji \U0001F600\U0001F44D\U0001F3FD family \U0001F468\u200d\U0001F469\u200d\U0001F467",
    "numbers 1234567 and 3.14159, 1e10 and 007 $5 + 6 = 11 <html> a@b.c ~^`|",
    "a" * 150 + " " + "\u00e9" * 101 + " " + "e\u0301" * 51,
    MULTI,
    "\u0e20\u0e32\u0e29\u0e32 \u0f40\u0f75\u0f71 \u302e\u0f75\U0001d165 \u0344\u0308",
    " ".join(["word"] * 125),
    " ".join(["word"] * 126) + " end",
    "\ufb01 ligature \u2167 \uff21\uff22\uff23 \u2460 \u00bd x\u00b2",
    "don't DON'T 'S 'll I'VE",
    "## ###abc## #",
    MULTI * 2,
    # the normalized path's windows (wp_api.c, TOKS_WP_WIN = 8192): ids that come only from a later window, and a
    # phase-1 token across the 8192nd byte (the cut moves to the next space)
    " " * 9000 + "hello <unk> world <UNK>!",
    ("x" * 101 + " ") * 90 + "<UNK> tail words <unk>",
    "a" * 8190 + "<UNK>" + " b <unk>",
]
FLAGS = [0, 1, 2, 4]
MODES = {0: "ALL", 1: "NONSPECIAL", 2: "NONE"}


def c_str(s: str) -> str:
    b = s.encode("utf-8")
    out, col = ['"'], 0
    for x in b:
        piece = ("\\%03o" % x) if (x in (0x22, 0x5C, 0x3F) or x < 0x20 or x >= 0x7F) else chr(x)
        out.append(piece)
        col += len(piece)
        if col > 100:
            out.append('"\n        "')
            col = 0
    out.append('"')
    return "".join(out)


def main() -> None:
    lines = ["/* generated by tests/c/test_wp_e2e.py from hf tokenizers 0.23.2; do not edit */"]
    lines.append("static const char *const WPE_TEXT[] = {")
    for t in TEXTS:
        lines.append("    " + c_str(t) + ",")
    lines.append("};")
    lines.append("static const uint32_t WPE_TEXT_LEN[] = { %s };" % ", ".join(str(len(t.encode())) for t in TEXTS))
    pins, cases, ids = [], [], []
    for pi, name in enumerate(PINS):
        path = os.path.join(ROOT, "wp-" + name)
        data = open(path, "rb").read()
        tj = json.loads(data)
        pad = tj["padding"]["pad_id"] if tj.get("padding") else 0xFFFFFFFF
        pins.append((name, hashlib.sha256(data).hexdigest(), pad))
        tok = O.load(path)
        for ti, t in enumerate(TEXTS):
            for fl in FLAGS:
                v = tok.encode(t, mode=MODES[fl & 3], add_special_tokens=not (fl & 4))
                k = len(v)
                while k > 0 and v[k - 1] == pad:
                    k -= 1
                cases.append((pi, ti, 0, fl, len(v), k, len(ids)))
                ids.extend(v[:k])
            for fl in (0, 2):
                _n, ends = tok.pieces(t, mode=MODES[fl])
                cases.append((pi, ti, 1, fl, len(ends), len(ends), len(ids)))
                ids.extend(ends)
    lines.append("typedef struct { const char *name; const char *sha256; uint32_t pad_id; } wpe_pin;")
    lines.append("static const wpe_pin WPE_PIN[] = {")
    for name, sha, pad in pins:
        lines.append('    { "wp-%s", "%s", %du },' % (name, sha, pad))
    lines.append("};")
    lines.append("typedef struct { uint8_t pin, text, op, flags; uint32_t n, stored, off; } wpe_case;   /* op 0 encode, 1 pieces */")
    lines.append("static const wpe_case WPE_CASE[] = {")
    for c in cases:
        lines.append("    { %d, %d, %d, %d, %d, %d, %d }," % c)
    lines.append("};")
    lines.append("static const uint32_t WPE_IDS[] = {")
    for i in range(0, len(ids), 16):
        lines.append("    " + ", ".join(str(x) for x in ids[i:i + 16]) + ",")
    lines.append("};")
    out = os.path.join(HERE, "test_wp_e2e.inc")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out, len(cases), "cases,", len(ids), "stored values")


if __name__ == "__main__":
    main()
