/*
 * test_k3_o200k.c: hand cases for the o200k K3 c twin (docs/templates/o200k.md, kernels.md §2-3): every
 * rule and every note with hf's pieces (tests/k3/o200k_golden.h), both variants (o200k, nemo), all
 * strings of up to 3-4 atoms over a representative alphabet, invalid utf-8 at every position, caps
 * 1..n with resume equivalence, guard-page geometry (no read at/past len; lengths 0..255, start
 * alignment 0..63), the parameter bits the template ignores. The kimi variant (§6: Han runs, Han out of
 * the case groups, no '/' tail) runs everywhere too, its golden pieces from tiktoken 0.14.0 itself.
 *
 * Two oracles: hf 0.23.2's pieces for the golden cases (generated by tests/k3/o200k_gen.py golden), and
 * a reference scanner restating the doc's rules over a decoded atom array (written from the prose, not
 * from the kernel's streaming code) for everything else, including invalid utf-8 (hf cannot see it).
 * The outer oracle at scale is tests/k3/o200k_run.sh on a lab host; this file is the fast gate.
 */
/* kernels.h -> core.h redeclares memcpy/memset/memcmp (freestanding core): it must come before
 * <string.h>, whose secure _chk macros would collide with the declarations. */
#include "../../src/core/classes.h"
#include "../../src/core/compile.h"
#include "../../src/gen/han_ranges.h"
#include "../../src/core/kernels.h"
#include "../../src/core/layout.h"
#include "../common/guard.h"

/* the tier under test: the c twin by default; for an asm tier, build this file by hand with
 * -DK3_SCAN=toks_k3_scan_o200k_<tier> plus its .S file */
#ifndef K3_SCAN
#define K3_SCAN toks_k3_scan_o200k_c
#endif
uint64_t K3_SCAN(const toks_tables *t, toks_k3_args *a);
/* the tier's whole kernel: an asm part runs with the c twin's stretches (kernels.h toks_k3_tier) */
static uint64_t k3_scan(const toks_tables *t, toks_k3_args *a)
{
    return toks_k3_tier(K3_SCAN, toks_k3_scan_o200k_c, t, a);
}

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { uint8_t v; const char *s; uint32_t len, first, n; } golden_case;
#include "../k3/o200k_golden.h"

/* ---------------------------------------------------------------- variants and tables */

typedef struct { const char *name; uint32_t params; } variant;
#define NV 3
static const variant VARIANTS[NV] = {
    { "o200k", TOKS_TP_CONTR_CI | TOKS_TP_DIGITS_1_3 },
    { "nemo",  TOKS_TP_CONTR_NONE | TOKS_TP_DIGITS_1 },
    { "kimi",  TOKS_TP_CONTR_CI | TOKS_TP_DIGITS_1_3 | TOKS_TP_HAN | TOKS_TP_NO_SLASH },
};

static uint8_t cls_buf[128 + 2 * 0x1100 + 0x1100 * 256];
static uint8_t cls_buf_han[128 + 2 * 0x1100 + 0x1100 * 256];
static toks_class_tables CT, CTK;               /* plain; kimi's: classes.c's TOKS_CLASSES_HAN build */
static toks_class_tables CTR;                   /* kimi's reference: CT plus TOKS_C_HAN set here by hand */
static toks_tables TT[NV];

/* the reference for kimi's tables: the plain build with every block a Han range touches copied and the bit set
 * by hand, from the generated table (src/gen/han_ranges.c, tools/gen/han.py: tiktoken's own \p{Han}); classes.c's
 * TOKS_CLASSES_HAN build must equal it on every scalar value (check_han), and the table its recorded hash. */
static uint16_t kimi_s1[0x1100];
static uint8_t kimi_s2[0x1100 * 256];

static void build_tables(void)
{
    int used = toks_classes_build(0u, cls_buf, sizeof cls_buf, &CT);   /* marks keep base P */
    if (used <= 0) { fprintf(stderr, "classes build failed\n"); exit(2); }
    /* kimi: stage 2 copied block by block, every block a Han range touches made private, the bit set */
    uint32_t nb = CT.n_blocks;
    memcpy(kimi_s1, CT.stage1, sizeof kimi_s1);
    memcpy(kimi_s2, CT.stage2, (size_t)nb * 256u);
    for (size_t r = 0; r < TOKS_HAN_N; r++) {                                 /* bound: TOKS_HAN_N ranges */
        for (uint32_t cp = toks_han_ranges[r][0]; cp <= toks_han_ranges[r][1]; cp++) {   /* bound: the range */
            uint32_t hi = cp >> 8;
            if (kimi_s1[hi] < CT.n_blocks) {                                   /* still shared: copy */
                memcpy(kimi_s2 + (size_t)nb * 256u, CT.stage2 + (size_t)kimi_s1[hi] * 256u, 256u);
                kimi_s1[hi] = (uint16_t)nb++;
            }
            kimi_s2[(size_t)kimi_s1[hi] * 256u + (cp & 0xFFu)] |= TOKS_C_HAN;
        }
    }
    CTR = CT;
    CTR.stage1 = kimi_s1;
    CTR.stage2 = kimi_s2;
    CTR.n_blocks = nb;
    used = toks_classes_build(TOKS_CLASSES_HAN, cls_buf_han, sizeof cls_buf_han, &CTK);
    if (used <= 0) { fprintf(stderr, "classes build (TOKS_CLASSES_HAN) failed\n"); exit(2); }
    for (int v = 0; v < NV; v++) {
        const toks_class_tables *c = v == 2 ? &CTK : &CT;
        toks_tables *t = &TT[v];
        memset(t, 0, sizeof *t);
        t->magic = TOKS_TABLES_MAGIC;
        t->version = TOKS_TABLES_VERSION;
        t->tmpl = TOKS_TMPL_O200K;
        t->tmpl_params = VARIANTS[v].params;
        t->cls_ascii = c->ascii;
        t->cls_stage1 = c->stage1;
        t->cls_stage2 = c->stage2;
        t->cls_nblocks = c->n_blocks;
        int64_t cf = toks_compile_cls_flags(t);         /* TOKS_TF_CJK_L / _B, as the compiler sets them */
        if (cf < 0) { fprintf(stderr, "class tables break kernels.md §2\n"); exit(2); }
        t->flags = (uint32_t)cf;
    }
}

/* ---------------------------------------------------------------- the reference scanner */

#define MAXCASE 4096
#define NONE (-1)
#define BASE(c) ((c) & 0x07)

typedef struct { uint32_t off, cp; uint8_t cls; } ratom;
static ratom RA[MAXCASE + 1];
static int M;                                         /* atoms in RA */

/* §2: a well-formed sequence is one atom; any other byte is a one-byte P atom without flags. With han
 * (§6) a Han atom keeps its base class and TOKS_C_HAN but leaves both case groups. */
static void decode(const toks_class_tables *ct, int han, const uint8_t *text, uint64_t len)
{
    uint64_t i = 0;
    M = 0;
    while (i < len) {                                 /* bound: len (>= 1 byte per atom) */
        uint32_t k = toks_utf8_len(text + i, len - i);
        ratom a;
        a.off = (uint32_t)i;
        if (k == 0u) { a.cp = text[i]; a.cls = TOKS_CLS_P; k = 1u; }
        else if (k == 1u) { a.cp = text[i]; a.cls = ct->ascii[text[i]]; }
        else { a.cp = toks_cp_decode(text + i, k); a.cls = toks_class_of(ct, a.cp); }
        if (han && (a.cls & TOKS_C_HAN) != 0u) { a.cls = (uint8_t)(a.cls & ~(TOKS_CLS_UPPER | TOKS_CLS_LOWER)); }
        RA[M++] = a;
        i += k;
    }
    RA[M].off = (uint32_t)len;
}

static int up(int j) { return j < M && (RA[j].cls & TOKS_CLS_UPPER) != 0; }
static int lo(int j) { return j < M && (RA[j].cls & TOKS_CLS_LOWER) != 0; }
static int base(int j) { return j < M ? BASE(RA[j].cls) : 0xFF; }   /* absent atoms: no class */

/* K(e): the contraction suffix at atom e, in atoms (0 when absent or with CONTR_NONE) */
static int K(int e, int contr)
{
    if (!contr || e + 1 >= M || RA[e].cp != 0x27u) { return 0; }
    uint32_t c1 = RA[e + 1].cp;
    if (c1 == 's' || c1 == 'S' || c1 == 't' || c1 == 'T' || c1 == 'm' || c1 == 'M' || c1 == 'd' ||
        c1 == 'D' || (RA[e + 1].cls & TOKS_CLS_FOLD_S) != 0) { return 2; }
    if (e + 2 < M) {
        uint32_t c2 = RA[e + 2].cp;
        if (((c1 == 'r' || c1 == 'R') && (c2 == 'e' || c2 == 'E')) ||
            ((c1 == 'v' || c1 == 'V') && (c2 == 'e' || c2 == 'E')) ||
            ((c1 == 'l' || c1 == 'L') && (c2 == 'l' || c2 == 'L'))) { return 3; }
    }
    return 0;
}

static int u_of(int s)
{
    int u = s;
    while (up(u)) { u++; }                            /* bound: M */
    return u;
}

/* L1(s): [UP]*[LO]+K?  -> end atom index or NONE */
static int L1(int s, int contr)
{
    int u = u_of(s);
    if (lo(u)) {
        int e = u;
        while (lo(e)) { e++; }                        /* bound: M */
        return e + K(e, contr);
    }
    for (int j = u - 1; j >= s; j--) {               /* bound: u - s; the LAST LO atom of [s, u) */
        if (lo(j)) { return j + 1 + K(j + 1, contr); }
    }
    return NONE;
}

/* L2(s): [UP]+[LO]*K? */
static int L2(int s, int contr)
{
    if (!up(s)) { return NONE; }
    int e = u_of(s);
    while (lo(e)) { e++; }                            /* bound: M */
    return e + K(e, contr);
}

static uint64_t ref_scan(uint32_t params, const toks_class_tables *ct, const uint8_t *text, uint64_t len,
                         uint64_t cap, uint32_t *ends)
{
    int contr = (params & TOKS_TP_CONTR_MASK) != TOKS_TP_CONTR_NONE;
    int digits1 = (params & TOKS_TP_DIGITS_MASK) == TOKS_TP_DIGITS_1;
    int han = (params & TOKS_TP_HAN) != 0u, slash = (params & TOKS_TP_NO_SLASH) == 0u;
    uint64_t n = 0;
    decode(ct, han, text, len);
    int i = 0;
    while (i < M && n < cap) {                        /* bound: M pieces at most */
        int b = base(i), e = NONE;
        /* O0 (§6) */
        if (han && (RA[i].cls & TOKS_C_HAN) != 0u) {
            e = i + 1;
            while (e < M && (RA[e].cls & TOKS_C_HAN) != 0u) { e++; }                 /* bound: M */
        }
        /* O1 */
        else if (b == TOKS_CLS_P || b == TOKS_CLS_WS) {
            e = L1(i + 1, contr);
            if (e == NONE) { e = L1(i, contr); }
            if (e == NONE) { e = L2(i + 1, contr); }
        } else if (b == TOKS_CLS_L) {
            e = L1(i, contr);
            if (e == NONE) { e = L2(i, contr); }
        }
        /* O2 */
        if (e == NONE && b == TOKS_CLS_N) {
            e = i + 1;
            while (!digits1 && e < M && e < i + 3 && base(e) == TOKS_CLS_N) { e++; }   /* bound: 3 */
        }
        /* O3 */
        if (e == NONE) {
            int j = b == TOKS_CLS_P ? i : (RA[i].cp == 0x20u && base(i + 1) == TOKS_CLS_P ? i + 1 : NONE);
            if (j != NONE) {
                e = j;
                while (base(e) == TOKS_CLS_P) { e++; }                                  /* bound: M */
                while (e < M && (RA[e].cp == 0x0Du || RA[e].cp == 0x0Au || (slash && RA[e].cp == 0x2Fu))) { e++; }
            }
        }
        /* O4-O6 */
        if (e == NONE) {
            int k = i, t;
            while (base(k) == TOKS_CLS_WS || base(k) == TOKS_CLS_NL) { k++; }            /* bound: M */
            for (t = k - 1; t >= i && base(t) != TOKS_CLS_NL; t--) { }                   /* bound: k - i */
            if (t >= i) { e = t + 1; }
            else if (k == M) { e = k; }
            else if (k - i >= 2) { e = k - 1; }
            else { e = k; }
        }
        ends[n++] = RA[e].off;
        i = e;
    }
    return n;
}

/* ---------------------------------------------------------------- harness */

static int failures;
static uint64_t checks;

static void dump(const char *what, const uint32_t *e, uint64_t n)
{
    fprintf(stderr, "  %s:", what);
    for (uint64_t i = 0; i < n; i++) { fprintf(stderr, " %" PRIu32, e[i]); }
    fprintf(stderr, "\n");
}

static void fail_text(const char *label, const variant *v, const uint8_t *text, uint64_t len)
{
    fprintf(stderr, "FAIL %s %s: text", v->name, label);
    for (uint64_t i = 0; i < len && i < 48u; i++) { fprintf(stderr, " %02X", text[i]); }
    fprintf(stderr, "\n");
}

/* kernel == expected (or the ref when expected is NULL); contract; resume with caps 1..maxcap */
static void run_case(int vi, const char *label, const uint8_t *text, uint64_t len,
                     const uint32_t *expect, uint64_t en, uint64_t maxcap)
{
    static uint32_t want[MAXCASE], got[MAXCASE], acc[MAXCASE];
    const variant *v = &VARIANTS[vi];
    const toks_tables *t = &TT[vi];
    uint64_t rn = ref_scan(v->params, vi == 2 ? &CTK : &CT, text, len, MAXCASE, want);
    if (expect != NULL) {                             /* the ref must reproduce hf / the hand value */
        if (rn != en || memcmp(want, expect, (size_t)en * 4u) != 0) {
            if (failures < 20) { fail_text(label, v, text, len); dump("expect", expect, en); dump("ref", want, rn); }
            failures++;
            return;
        }
    }
    toks_k3_args a;
    memset(&a, 0, sizeof a);
    a.text = text; a.len = len; a.pos = 0; a.ends = got; a.cap = MAXCASE;
    uint64_t kn = k3_scan(t, &a);
    checks++;
    if (kn != rn || memcmp(want, got, (size_t)rn * 4u) != 0 || a.n != kn) {
        if (failures < 20) { fail_text(label, v, text, len); dump("want", want, rn); dump("got", got, kn); }
        failures++;
        return;
    }
    uint64_t prev = 0;                                /* ends strictly increase in (pos, len] */
    for (uint64_t i = 0; i < rn; i++) {
        if (got[i] <= prev || got[i] > len) {
            if (failures < 20) { fail_text(label, v, text, len); fprintf(stderr, "  end out of order\n"); }
            failures++;
            return;
        }
        prev = got[i];
    }
    if ((rn != 0u && a.pos != got[rn - 1u]) || (rn == 0u && (a.pos != 0u || len != 0u))) {
        if (failures < 20) { fail_text(label, v, text, len); fprintf(stderr, "  pos %" PRIu64 "\n", a.pos); }
        failures++;
        return;
    }
    if (maxcap > rn + 1u) { maxcap = rn + 1u; }
    for (uint64_t cap = 1; cap <= maxcap; cap++) {    /* resume: every cap tiles to the same pieces */
        uint64_t pos = 0, an = 0;
        while (pos < len) {                           /* bound: pieces (each call advances >= 1) */
            memset(&a, 0, sizeof a);
            a.text = text; a.len = len; a.pos = pos; a.ends = acc + an; a.cap = cap;
            uint64_t c = k3_scan(t, &a);
            if (c == 0u || c > cap || a.pos <= pos || a.n != c) {
                if (failures < 20) { fail_text(label, v, text, len); fprintf(stderr, "  cap %" PRIu64 " stalls\n", cap); }
                failures++;
                return;
            }
            an += c;
            pos = a.pos;
        }
        if (an != rn || memcmp(acc, want, (size_t)rn * 4u) != 0) {
            if (failures < 20) { fail_text(label, v, text, len); fprintf(stderr, "  resume cap %" PRIu64 "\n", cap); }
            failures++;
            return;
        }
        checks++;
    }
}

static void both(const char *label, const uint8_t *text, uint64_t len)   /* every variant */
{
    for (int v = 0; v < NV; v++) { run_case(v, label, text, len, NULL, 0, MAXCASE); }   /* bound: NV */
}

/* a hand expectation (from the rules; used for invalid utf-8, which hf cannot see) */
static void expect1(int vi, const char *label, const char *s, uint64_t len, const uint32_t *e, uint64_t en)
{
    run_case(vi, label, (const uint8_t *)s, len, e, en, MAXCASE);
}

static uint64_t utf8(uint32_t cp, uint8_t *o)
{
    if (cp < 0x80u) { o[0] = (uint8_t)cp; return 1; }
    if (cp < 0x800u) { o[0] = (uint8_t)(0xC0u | (cp >> 6)); o[1] = (uint8_t)(0x80u | (cp & 0x3Fu)); return 2; }
    if (cp < 0x10000u) {
        o[0] = (uint8_t)(0xE0u | (cp >> 12)); o[1] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu));
        o[2] = (uint8_t)(0x80u | (cp & 0x3Fu));
        return 3;
    }
    o[0] = (uint8_t)(0xF0u | (cp >> 18)); o[1] = (uint8_t)(0x80u | ((cp >> 12) & 0x3Fu));
    o[2] = (uint8_t)(0x80u | ((cp >> 6) & 0x3Fu)); o[3] = (uint8_t)(0x80u | (cp & 0x3Fu));
    return 4;
}

/* classes.c's Han bit (TOKS_CLASSES_HAN) against the hand-built reference on every scalar value; bit 7 clear
 * in every build without the flag; the flag word checks. */
static void check_han(void)
{
    static uint8_t buf[128 + 2 * 0x1100 + 0x1100 * 256];
    toks_class_tables ml;
    uint32_t n_han = 0u, bad = 0u, bit7 = 0u;
    if (toks_classes_build(TOKS_CLASSES_MARKS_ARE_LETTERS, buf, sizeof buf, &ml) <= 0) {
        fprintf(stderr, "classes build (MARKS_ARE_LETTERS) failed\n");
        exit(2);
    }
    for (uint32_t cp = 0u; cp <= 0x10FFFFu; cp++) {                    /* bound: every code point */
        uint8_t r = toks_class_of(&CTR, cp), k = toks_class_of(&CTK, cp);
        if (r != k) {
            if (bad < 8u) { fprintf(stderr, "FAIL han U+%04X: classes.c %#x, reference %#x\n", cp, k, r); }
            bad++;
        }
        n_han += (k & TOKS_C_HAN) != 0u;
        bit7 += ((toks_class_of(&CT, cp) | toks_class_of(&ml, cp)) & TOKS_C_HAN) != 0u;
    }
    checks += 0x110000u;
    failures += (int)bad;
    /* the generated table: ascending and disjoint, its hash the one recorded, its size the recorded one (99,030 =
     * regex-syntax 0.8.11's Script=Han); U+3001 is Han only by Script_Extensions; U+3006 is Lo, not Han */
    uint8_t raw[TOKS_HAN_N * 8u], d[32];
    char hex[65];
    uint32_t sum = 0u, ordered = 1u;
    for (uint32_t r = 0; r < TOKS_HAN_N; r++) {                              /* bound: TOKS_HAN_N */
        for (uint32_t k = 0; k < 2u; k++) {
            uint32_t v = toks_han_ranges[r][k];
            for (uint32_t b = 0; b < 4u; b++) { raw[r * 8u + k * 4u + b] = (uint8_t)(v >> (8u * b)); }
        }
        sum += toks_han_ranges[r][1] - toks_han_ranges[r][0] + 1u;
        ordered &= toks_han_ranges[r][0] <= toks_han_ranges[r][1] &&
                   (r == 0u || toks_han_ranges[r][0] > toks_han_ranges[r - 1u][1] + 1u);
    }
    toks_sha256(raw, sizeof raw, d);
    for (int i = 0; i < 32; i++) { snprintf(hex + 2 * i, 3, "%02x", d[i]); }
    checks += 8u;
    if (strcmp(hex, TOKS_HAN_SHA256) != 0) { fprintf(stderr, "FAIL han table sha256 %s\n", hex); failures++; }
    if (ordered == 0u) { fprintf(stderr, "FAIL han table: ranges not ascending and disjoint\n"); failures++; }
    if (sum != TOKS_HAN_CODEPOINTS || TOKS_HAN_CODEPOINTS != 99030u) {
        fprintf(stderr, "FAIL han table: %u code points, header %u, want 99030\n", sum, TOKS_HAN_CODEPOINTS);
        failures++;
    }
    if (n_han != 99030u) { fprintf(stderr, "FAIL han: %u code points, want 99030\n", n_han); failures++; }
    if (bit7 != 0u) { fprintf(stderr, "FAIL han: bit 7 set in %u classes without the flag\n", bit7); failures++; }
    if ((toks_class_of(&CTK, 0x3001u) & TOKS_C_HAN) != 0u || (toks_class_of(&CTK, 0x3006u) & TOKS_C_HAN) != 0u ||
        (toks_class_of(&CTK, 0x3005u) & TOKS_C_HAN) == 0u || (toks_class_of(&CTK, 0x323AFu) & TOKS_C_HAN) == 0u) {
        fprintf(stderr, "FAIL han: U+3001 / U+3006 / U+3005 / U+323AF\n");
        failures++;
    }
    if (toks_classes_bytes(0x4u) != 0u || toks_classes_build(0x4u, buf, sizeof buf, &ml) != TOKS_CLASSES_E_FLAGS) {
        fprintf(stderr, "FAIL classes: an unknown class_flags bit is accepted\n");
        failures++;
    }
    if (toks_classes_bytes(TOKS_CLASSES_HAN | TOKS_CLASSES_MARKS_ARE_LETTERS) != sizeof buf) {
        fprintf(stderr, "FAIL classes: bytes for the known flags\n");
        failures++;
    }
}

/* ---------------------------------------------------------------- cases */

int main(void)
{
    build_tables();
    check_han();

    /* the golden cases: hf 0.23.2's pieces for every rule and note of docs/templates/o200k.md */
    for (size_t g = 0; g < sizeof GOLDEN / sizeof GOLDEN[0]; g++) {   /* bound: the table */
        char label[48];
        snprintf(label, sizeof label, "golden #%zu", g);
        run_case(GOLDEN[g].v, label, (const uint8_t *)GOLDEN[g].s, GOLDEN[g].len,
                 GOLDEN_ENDS + GOLDEN[g].first, GOLDEN[g].n, MAXCASE);
    }

    /* every string of 0..3 atoms over one representative per behaviour, 4 atoms over a smaller set */
    {
        static const uint32_t rep[] = {
            'A', 'a', 0x1C5, 0x2B0, 0x4E2D, 0x301, '5', ' ', '\t', 0x3000, '\r', '\n', '!', '/', '\'',
            's', 'S', 'l', 'e', 0x17F, 0x1F600, 0xE9, 0x660, 0x93E, 0x3007, 0x2E80, 0x3005, 0x16FF0
        };
        static const uint32_t small[] = { 'A', 'a', 0x4E2D, 0x301, '5', ' ', '\n', '!', '/', '\'', 's', 0x3007 };
        const size_t nr = sizeof rep / sizeof rep[0], ns = sizeof small / sizeof small[0];
        uint8_t buf[32];
        for (size_t x = 0; x < nr * nr * nr + nr * nr + nr + 1u; x++) {   /* bound: 28^3 + 28^2 + 28 + 1 */
            size_t len_atoms = x == 0u ? 0u : x <= nr ? 1u : x <= nr + nr * nr ? 2u : 3u;
            size_t idx = x == 0u ? 0u : len_atoms == 1u ? x - 1u : len_atoms == 2u ? x - 1u - nr : x - 1u - nr - nr * nr;
            uint64_t n = 0;
            for (size_t k = 0; k < len_atoms; k++) { n += utf8(rep[idx % nr], buf + n); idx /= nr; }
            for (int v = 0; v < NV; v++) { run_case(v, "rep<=3", buf, n, NULL, 0, 4); }   /* bound: NV */
        }
        for (size_t x = 0; x < ns * ns * ns * ns; x++) {                  /* bound: 12^4 */
            size_t idx = x;
            uint64_t n = 0;
            for (int k = 0; k < 4; k++) { n += utf8(small[idx % ns], buf + n); idx /= ns; }
            for (int v = 0; v < NV; v++) { run_case(v, "small4", buf, n, NULL, 0, 5); }   /* bound: NV */
        }
    }

    /* invalid utf-8: P atoms without flags -- a letter prefix, a punctuation atom, never a case atom.
     * Hand values from §2-§3 (hf cannot see invalid utf-8), checked against both the ref and the kernel. */
    {
        static const uint32_t e_ffabc[] = { 4 }, e_affb[] = { 1, 3 }, e_itc5[] = { 2, 4 }, e_xfold[] = { 4 },
                              e_xfold_nemo[] = { 1, 4 }, e_mark[] = { 2 }, e_ccbang[] = { 2 },
                              e_ffmark[] = { 3 }, e_tail[] = { 4 };
        expect1(0, "FF abc", "\xFF" "abc", 4, e_ffabc, 1);              /* the prefix of a letter run */
        expect1(0, "a FF b", "a\xFF" "b", 3, e_affb, 2);                /* a | FF b */
        expect1(0, "it' C5", "it'\xC5", 4, e_itc5, 2);                  /* a cut U+017F is no suffix */
        expect1(0, "x' U+017F", "x'\xC5\xBF", 4, e_xfold, 1);           /* the suffix 'ſ */
        expect1(1, "x' U+017F nemo", "x'\xC5\xBF", 4, e_xfold_nemo, 2); /* nemo: x | 'ſ */
        expect1(0, "U+0301", "\xCC\x81", 2, e_mark, 1);                 /* a whole mark */
        expect1(0, "CC !", "\xCC!", 2, e_ccbang, 1);                    /* a cut mark is P: CC! */
        expect1(0, "FF U+0301", "\xFF\xCC\x81", 3, e_ffmark, 1);        /* FF prefixes the mark */
        expect1(0, "! FF LF /", "!\xFF\n/", 4, e_tail, 1);              /* P run, then the tail */
    }
    {   /* every ill-formed kind at every position: kernel == ref */
        static const uint8_t salad[] = {
            'a', 0xC3, 0xA9, 'B', 0xE0, 0x80, 0x80, 'c',     /* overlong E0 80 80 */
            0xF0, 0x9F, 0x98, 'd',                            /* truncated 4-byte */
            0x80, 'E',                                         /* lone continuation */
            0xC2, 'f', '\'', 0xC5,                            /* C2 then non-continuation; ' then cut ſ */
            0xED, 0xA0, 0x80, 'g',                            /* encoded surrogate */
            0xF4, 0x90, 0x80, 0x80, 'h',                       /* above U+10FFFF */
            0xC0, 0xAF, '/', '\n', '/',                        /* overlong 2-byte, then a tail */
            0xE0, 0x9F, 0xBF, 0xCC, 0x81, 'J',                /* E0 out of range, then a mark */
            0xF0, 0x80, 0x80, 0x80, 'k', '\'', 'S'             /* overlong 4-byte, then a suffix */
        };
        both("utf8 salad", salad, sizeof salad);
        for (uint64_t cut = 0; cut <= sizeof salad; cut++) {   /* bound: salad length */
            both("salad cut", salad, cut);
            both("salad tail", salad + cut, sizeof salad - cut);
        }
        for (int x = 0x80; x < 0x100; x++) {                     /* bound: 128 bad bytes */
            const uint8_t ctx[][4] = {
                { 'a', (uint8_t)x, 'b', 0 }, { 'A', (uint8_t)x, 'B', 0 }, { (uint8_t)x, 0xCC, 0x81, 0 },
                { '\'', (uint8_t)x, 's', 0 }, { '!', (uint8_t)x, '\n', '/' }, { ' ', (uint8_t)x, 'a', 0 },
                { 'x', '\'', (uint8_t)x, 0 }, { (uint8_t)x, 0, 0, 0 }
            };
            const uint64_t ctxlen[] = { 3, 3, 3, 3, 4, 3, 3, 1 };
            for (size_t c = 0; c < sizeof ctxlen / sizeof ctxlen[0]; c++) {   /* bound: 8 contexts */
                both("bad byte", ctx[c], ctxlen[c]);
            }
        }
    }

    /* the template ignores every parameter bit but CONTR and DIGITS (docs/templates/o200k.md §1) */
    {
        static const char *soup = "Hello, world! It's 2024.\nDON'T PANIC/42\r\n  \xE4\xB8\xAD" "A's 12345 !/\n/x";
        static uint32_t e0[MAXCASE], e1[MAXCASE];
        const uint64_t len = strlen(soup);
        for (int vi = 0; vi < NV; vi++) {
            toks_tables t2 = TT[vi];
            toks_k3_args a;
            memset(&a, 0, sizeof a);
            a.text = (const uint8_t *)soup; a.len = len; a.ends = e0; a.cap = MAXCASE;
            uint64_t n0 = k3_scan(&TT[vi], &a);
            t2.tmpl_params |= TOKS_TP_LPREFIX_ANY | TOKS_TP_PUNCT_NL | TOKS_TP_WS_NL | 0xFFFFFE00u;
            memset(&a, 0, sizeof a);
            a.text = (const uint8_t *)soup; a.len = len; a.ends = e1; a.cap = MAXCASE;
            uint64_t n1 = k3_scan(&t2, &a);
            checks++;
            if (n0 != n1 || memcmp(e0, e1, (size_t)n0 * 4u) != 0) {
                fprintf(stderr, "FAIL %s: ignored parameter bits change the pieces\n", VARIANTS[vi].name);
                failures++;
            }
        }
    }

    /* guard-page geometry: deterministic text, lengths 0..255, end flush against a no-access page and
     * start right after one at every alignment 0..63 (kernels.md §1; SPEC §14.3) */
    {
        uint64_t seed = 0x4F32303030ull;
        static const uint8_t pool[] =
            "aAs'tl/!5 \t\r\n\xC3\xA9\xC5\xBF\xE4\xB8\xAD\xCC\x81\xC7\x85\xCA\xB0\xC2\xA0\xE3\x80\x80"
            "\xF0\x9F\x98\x80\x80\xFF\xC5\xE3\x80\x87\xE2\xBA\x80\xE3\x80\x85";
        uint8_t buf[256];
        for (uint64_t len = 0; len <= 255; len++) {            /* bound: 256 lengths */
            for (uint64_t i = 0; i < len; i++) {               /* bound: len */
                buf[i] = pool[guard_rng(&seed) % (sizeof pool - 1u)];
            }
            for (int where = 0; where < 2; where++) {           /* bound: 2 guard kinds */
                for (size_t off = 0; off < (where == GUARD_START ? 64u : 1u); off++) {   /* bound: 64 */
                    guard_buf g = { 0 };
                    uint8_t *p = guard_alloc(&g, (size_t)len, where, off);
                    if (!p) { fprintf(stderr, "guard_alloc failed\n"); return 2; }
                    memcpy(p, buf, (size_t)len);
                    uint64_t mc = (where == GUARD_END || off == 0u) ? MAXCASE : 1u;
                    for (int v = 0; v < NV; v++) { run_case(v, "guard", p, len, NULL, 0, mc); }   /* bound: NV */
                    guard_free(&g);
                }
            }
        }
    }

    printf("test_k3_o200k: %" PRIu64 " checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
