from os import PathLike
from typing import AbstractSet, Any, Collection, Literal, Sequence

from collections.abc import Buffer

ABI: tuple[int, int]
__version__: str
MAX_TEXT: int
ID_ADDED: int
ID_SPECIAL: int
ID_BYTE: int

_Text = str | Buffer
_Ids = Sequence[int] | Buffer
_Mode = Literal["all", "nonspecial", "none"] | None
_Tier = Literal["auto", "scalar", "neon", "avx2", "avx512"] | None

class Error(Exception):
    code: int
    name: str

class DecodeStream:
    def push(self, ids: int | _Ids, /) -> str: ...
    def flush(self) -> str: ...

class Encoding:
    """hf tokenizers' Encoding of one text; every attribute is a new list"""
    @property
    def ids(self) -> list[int]: ...
    @property
    def type_ids(self) -> list[int]: ...
    @property
    def tokens(self) -> list[str]: ...
    @property
    def attention_mask(self) -> list[int]: ...
    @property
    def special_tokens_mask(self) -> list[int]: ...
    @property
    def overflowing(self) -> list[Encoding]: ...
    @property
    def n_sequences(self) -> int: ...
    def __len__(self) -> int: ...

class Tokenizer:
    encode_special_tokens: bool
    @property
    def source(self) -> str | bytes: ...
    @property
    def n_vocab(self) -> int: ...
    @property
    def max_token_value(self) -> int: ...
    @property
    def eot_token(self) -> int: ...
    @property
    def special_tokens_set(self) -> set[str]: ...
    @property
    def name(self) -> str: ...
    @classmethod
    def from_file(cls, path: str | bytes | PathLike[str] | PathLike[bytes], *, tier: _Tier = None,
                  cache_mib: int = 0) -> Tokenizer: ...
    @classmethod
    def from_str(cls, json: str, *, tier: _Tier = None) -> Tokenizer: ...
    @classmethod
    def from_buffer(cls, data: Buffer, *, tier: _Tier = None) -> Tokenizer: ...
    def encode(self, text: _Text, *, add_special_tokens: bool = True, added_tokens: _Mode = None,
               continuation: bool = False, allowed_special: Literal["all"] | AbstractSet[str] = ...,
               disallowed_special: Literal["all"] | Collection[str] = ...) -> list[int]: ...
    def encode_ordinary(self, text: _Text, /) -> list[int]: ...
    def encode_ex(self, text: _Text, *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                  continuation: bool = False) -> Encoding: ...
    def encode_into(self, text: _Text, out: Buffer, *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                    continuation: bool = False) -> int: ...
    def encode_batch(self, texts: Sequence[_Text], *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                     continuation: bool = False) -> list[list[int]]: ...
    def encode_batch_ex(self, texts: Sequence[_Text], *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                        continuation: bool = False) -> list[Encoding]: ...
    def pieces(self, text: _Text, *, added_tokens: _Mode = None, continuation: bool = False) -> list[int]: ...
    def decode(self, ids: _Ids, skip_special_tokens: bool = True) -> str: ...
    def decode_batch(self, sequences: Sequence[_Ids], skip_special_tokens: bool = True) -> list[str]: ...
    def decode_bytes(self, ids: _Ids, /) -> bytes: ...
    def decode_bytes_batch(self, batch: Sequence[_Ids], *, num_threads: int = 8) -> list[bytes]: ...
    def decode_stream(self, skip_special_tokens: bool = False) -> DecodeStream: ...
    def token_bytes(self, id: int, /) -> bytes | None: ...
    def token_byte_values(self) -> list[bytes]: ...
    def token_to_id(self, token: str | Buffer, /) -> int | None: ...
    def encode_bound(self, n: int, /) -> int: ...
    def id_flags(self, id: int, /) -> int: ...
    def id_to_token(self, id: int, /) -> str | None: ...
    def num_special_tokens_to_add(self, is_pair: bool = False) -> int: ...
    def get_added_tokens_decoder(self) -> dict[int, AddedToken]: ...
    def get_vocab(self, with_added_tokens: bool = True) -> dict[str, int]: ...
    def get_vocab_size(self, with_added_tokens: bool = True) -> int: ...
    def info(self) -> dict[str, Any]: ...

from ._vocab import AddedToken as AddedToken
