from os import PathLike
from typing import Any, Literal, Sequence

from collections.abc import Buffer

ABI: tuple[int, int]
__version__: str
MAX_TEXT: int
ID_ADDED: int
ID_SPECIAL: int
ID_BYTE: int

_Text = str | Buffer
_Ids = Sequence[int] | Buffer
_Mode = Literal["all", "nonspecial", "none"] | None
_Tier = Literal["auto", "scalar", "neon", "avx2", "avx512"] | None

class Error(Exception):
    code: int
    name: str

class DecodeStream:
    def push(self, ids: int | _Ids, /) -> str: ...
    def flush(self) -> str: ...

class Tokenizer:
    encode_special_tokens: bool
    @property
    def source(self) -> str | bytes: ...
    @classmethod
    def from_file(cls, path: str | bytes | PathLike[str] | PathLike[bytes], *, tier: _Tier = None,
                  cache_mib: int = 0) -> Tokenizer: ...
    @classmethod
    def from_str(cls, json: str, *, tier: _Tier = None) -> Tokenizer: ...
    @classmethod
    def from_buffer(cls, data: Buffer, *, tier: _Tier = None) -> Tokenizer: ...
    def encode(self, text: _Text, *, add_special_tokens: bool = True, added_tokens: _Mode = None,
               continuation: bool = False) -> list[int]: ...
    def encode_into(self, text: _Text, out: Buffer, *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                    continuation: bool = False) -> int: ...
    def encode_batch(self, texts: Sequence[_Text], *, add_special_tokens: bool = True, added_tokens: _Mode = None,
                     continuation: bool = False) -> list[list[int]]: ...
    def pieces(self, text: _Text, *, added_tokens: _Mode = None, continuation: bool = False) -> list[int]: ...
    def decode(self, ids: _Ids, skip_special_tokens: bool = True) -> str: ...
    def decode_batch(self, sequences: Sequence[_Ids], skip_special_tokens: bool = True) -> list[str]: ...
    def decode_stream(self, skip_special_tokens: bool = False) -> DecodeStream: ...
    def token_bytes(self, id: int, /) -> bytes | None: ...
    def token_to_id(self, token: str | Buffer, /) -> int | None: ...
    def id_flags(self, id: int, /) -> int: ...
    def id_to_token(self, id: int, /) -> str | None: ...
    def get_vocab(self, with_added_tokens: bool = True) -> dict[str, int]: ...
    def get_vocab_size(self, with_added_tokens: bool = True) -> int: ...
    def info(self) -> dict[str, Any]: ...
